apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-lb
  namespace: kafka
spec:
  selector:
    app: kafka-ui
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: LoadBalancer
