apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-np
  namespace: kafka
spec:
  selector:
    app: kafka-ui
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
    nodePort: 31009  # Выберите порт в диапазоне 30000-32767
  type: NodePort
