apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  namespace: kafka
spec:
  kafka:
    version: 3.6.1
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9093
        type: nodeport
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      kraft.enabled: true
      zookeeper.connect: null
      controller.quorum.voters: "0@kafka-kafka-0.kafka-kafka-brokers.kafka.svc.cluster.local:9093"
      process.roles: "broker,controller"
      node.id: 0
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
  kafkaExporter: {}
  entityOperator:
    topicOperator: {}
    userOperator: {}
