# -*- mode: ruby -*-
# vi: set ft=ruby :vagr

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu_clean" # jammy-server-cloudimg-amd64-vagrant.box


  config.vm.network "forwarded_port", id: "ssh", host: 2022, guest: 22
  config.vm.network "public_network", bridge: "Intel(R) Wi-Fi 6 AX201 160MHz", ip: "192.168.0.16"

  config.vm.synced_folder '.', '/home/vagrant', disabled: true


  config.vm.provision "Package updating & installation", type: "shell", inline: <<-SHELL
   apt-get update
   echo "Hello from Ubuntu Virtual macine"
   apt-get install -y net-tools openssh-server
  SHELL


  config.vm.provision "SSH set up", type: "shell" do |s|
    ssh_prv_key = ""
    ssh_pub_key = ""
    if File.file?("keys/vm_key")
      ssh_prv_key = File.read("keys/vm_key")
      ssh_pub_key = File.readlines("keys/vm_key.pub").first.strip
    else
      puts "No SSH key found. Generate a pair of public and private keys."
    end
    s.inline = <<-SHELL
      if grep -sq "#{ssh_pub_key}" /home/vagrant/.ssh/authorized_keys; then
        echo "SSH keys already provisioned."
        exit 0;
      fi
      echo "SSH key provisioning."
      mkdir -p /home/vagrant/.ssh/
      touch /home/vagrant/.ssh/authorized_keys
      echo "#{ssh_pub_key}" >> /home/vagrant/.ssh/authorized_keys
      echo "#{ssh_pub_key}" > /home/vagrant/.ssh/id_rsa.pub
      chmod 644 /home/vagrant/.ssh/id_rsa.pub
      echo "#{ssh_prv_key}" > /home/vagrant/.ssh/id_rsa
      chmod 600 /home/vagrant/.ssh/id_rsa
      chown -R vagrant:vagrant /home/vagrant
      exit 0
    SHELL
  end

end
