{
 "title": "Frontend Statistics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Status Panel",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(django_http_responses_total_by_status_total[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests Info",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(django_http_requests_body_total_bytes_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_including_middlewares_seconds_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}