{
 "title": "Backend [Litestar]",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(litestar_requests_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "2XX Responses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(litestar_requests_total{status_code=~\"2.+\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "4XX Responses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(litestar_requests_total{status_code=~\"4.+\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Total Request Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(litestar_requests_total) by (status_code)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "3XX Responses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(litestar_requests_total{status_code=~\"3.+\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "5XX Responses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(litestar_requests_total{status_code=~\"5.+\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Number of Requests by Processing Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(litestar_request_duration_seconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(litestar_requests_total[$__rate_interval])) by(status_code)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}