{
 "title": "Backend Statistics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Duration of `/metrics` request (s)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(litestar_request_duration_seconds_bucket{status_code=\"200\", path=\"/metrics\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(litestar_requests_total{status_code=\"200\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Python GC Stats",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total{job=\"backend\"}",
     "legendFormat": "GC Generation: {{generation}}"
    }
   ]
  }
 ]
}