"""add book embedding

Revision ID: e0ecef335c53
Revises: a982fa0a126f
Create Date: 2025-05-06 17:50:38.456675

"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0ecef335c53"
down_revision: str | None = "a982fa0a126f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book", sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book", "embedding")
    # ### end Alembic commands ###
